name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 🔹 BUILD
      - name: Build (skip tests)
        run: |
          cd Springboot-ecommerce-main
          mvn clean install -DskipTests

      # 🔹 TEST
      - name: Run Tests
        run: |
          cd Springboot-ecommerce-main
          mvn test

      # 🔹 DEPLOY (Demo)
      - name: Deploy
        run: echo "Deploy success 🚀"
